### ISSUE TITLE
Scanning Templates with Variables

### ISSUE THREAD

**Issue by davidsonjon** [prisma-cloud-shiftleft/iac-scan-action#7]
# Behavior Observed

Templates with variables are not scanned.

# Configuration Information

When testing scanning using the samples from https://github.com/prisma-cloud-shiftleft/iac-samples/tree/main/CFT with the following configuration does not produce any results for templates that contain variables, other templates produce the expected results.

``` yaml
      - name: Run Scan on CFT
        uses: prisma-cloud-shiftleft/iac-scan-action@v1.1
        id: iac-scan
        with:
          prisma_api_url: 'https://api3.prismacloud.io'
          access_key: ${{ secrets.PRISMA_CLOUD_ACCESS_KEY }}
          secret_key: ${{ secrets.PRISMA_CLOUD_SECRET_KEY }}
          asset_name: 'cfn-templates'
          template_type: 'CFT'
          scan_path: ./CFT
          variable_files: ./CFT/cft_variables.json
          variables: AccessControl:PublicRead
```
